### ISSUE TITLE
Issue with commit not "kicking in"

### ISSUE THREAD

**Issue by WoodsterDK** [dbosoft/YaNco#255]
Hi,

I am trying to post some data to SAP.

I'm doing a "_context.CallFunction" for updating the values, it responds with success, but when I sequentially call "_context.CommitAndWait" nothing happens.

The call does not fail, but in SAP it seems like the commit never took place - any ideas?

**Comment by fw2568** [comment]
Hi,

could you please provide a full sample with code?

Thanks,
Frank

**Comment by WoodsterDK** [comment]
Hi Frank,

sure - this is basically what I try to do - code has been copy pasted a bit, but when I run with my specific function name and variables I end up with a succes response, and all return values are valid values.
I then step over 'commitAndWait' - no errors, but it looks like change is not being commited to SAP.

`


    internal class Program
    {
        static async Task Main(string[] args)
        {
            var settings = new Dictionary<string, string>
            {
                { "ashost", "dummy" },
                { "sysnr", "00" },
                { "client", "001" },
                { "user", "dummy" },
                { "passwd", "peng" },
                { "lang", "EN" }

            };

            var rfcConnnectionBuilder = new ConnectionBuilder(settings);


            using (var context = new RfcContext(rfcConnnectionBuilder.Build()))
            {
                Dictionary<string, object> _output = new Dictionary<string, object>();
                RfcErrorInfo rfcErrorInfo = new RfcErrorInfo();

                var task = Task.Run(async () =>
                {
                    var status = await _context.CallFunction("FUNCTION",
                    Input: f => f
                            .setField("INPUTFIELD", "INPUTVALUE")
                            ,
                        Output: f =>
                                        from data_return in f.MapStructure("RETURN", s => s.ToDictionary())

                                        select new Dictionary<string, object>
                                        {
                                        {"RETURN",data_return }
                                        }
                                    , cancelSource.Token)
                                    .Match(
                                        r => { _output = r; },
                                        l => { rfcErrorInfo = l; });


                });
                if (task != null)
                    task.Wait();

                if (task.Status == TaskStatus.RanToCompletion && rfcErrorInfo.Code == RfcRc.RFC_OK)
                {
                    Dictionary<string, string> RETURN = convertRFCStructToDictionary(_output["RETURN"]);

                    bool ErrorHasOccured = true;
                    string Data_Type = "";
                    string Data_ID = "";
                    string Data_Number = "";
                    string Data_Message = "";

                    if (RETURN != null &&  RETURN.Count > 0) 
                    {
                        Data_Type = RETURN.GetValue("TYPE").ToString();
                        Data_ID = RETURN.GetValue("ID").ToString();
                        Data_Number = RETURN.GetValue("NUMBER").ToString();
                        Data_Message = RETURN.GetValue("MESSAGE").ToString();

                        if (Data_Type == "S" )     // Criteria for success
                        {
                            _context.CommitAndWait(cancelSource.Token);
                        }
                    }
                }
            }
        }

        internal static Either<RfcErrorInfo, TDataContainer> setField<TDataContainer, T>(this Either<RfcErrorInfo, TDataContainer> self, string name, T value, bool addValue=true) where TDataContainer : IDataContainer
        {
            try
            {
                if (addValue)
                {
                    if (name != "" && value != null && !String.IsNullOrEmpty(value.ToString()))
                    {
                        self.SetField(name, value);
                    }
                }
            }
            catch (Exception ex)
            {

            }


            return self;
        }
    }
`

**Comment by WoodsterDK** [comment]
Hi Frank,
I have been doing some further tests today, and it seems some of the inputs are not being used correctly by the backend RFC in SAP - depending upon the mapping, but somehow still reports status OK - hence the commit has no impact, because the needed variables are not OK.
I will continue my hunt for the root cause - for now, I expect your function to be working 100% as intended.
Thanks for your response.

**Comment by fw2568** [comment]
Hi,

Ok then I will close the issue. Please note that there are also some potential problems in your code:

- You don't need to handle the result of the BAPI this way, instead you should use the [`HandleReturn`](https://github.com/dbosoft/YaNco/blob/a27637e44c6e92ed8bd9cd62cbab7bc69e9fa59d/src/YaNco.Core/FunctionalFunctionsExtensions.cs#L45) method to automatically set the function to left state if SAP returns an error. You don't have to return an S (success) message, because there are some BAPIs that never return a success. 

- You should not wrap async code in a Task.Run - you are already in an async program, this can lead to blocking code.
- Context.CommitAndWait is async to (EitherAsync) and should be awaited, too.

An example of using HandleReturn and CommitAndWait in one call can be found here: 
https://github.com/dbosoft/YaNco/blob/a27637e44c6e92ed8bd9cd62cbab7bc69e9fa59d/samples/netcore3.1/CreateSalesOrder/CreateSimpleSalesDocument.cs#L88

(the example uses HandleReturnTable, but it is the same for HandleReturn).

**Comment by WoodsterDK** [comment]
Hi Frank,

thanks for your inputs - I merely extracted the code into a sample program, so in real application it runs differently, and actually needs to run sequentiel.

But thanks a lot for taking time to look into it...
